# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Build and deploy to Azure Kubernetes Service

env:
  AZURE_CONTAINER_REGISTRY: registry16012026  # set this to the name of your container registry
  PROJECT_NAME: aks-deploy              # set this to your project's name
  RESOURCE_GROUP: aks-group         # set this to the resource group containing your AKS cluster
  CLUSTER_NAME: aks-cluster              # set this to the name of your AKS cluster
  REGISTRY_URL: registry16012026.azurecr.io           # set this to the URL of your registry
  # If you bake using helm:
  CHART_PATH: ./charts/aks-store-demo                   # set this to the path to your helm file
  #CHART_OVERRIDE_PATH: MY_OVERRIDE_FILES     # set this to an array of override file paths

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build image on ACR
      uses: azure/CLI@v2
      with:
        azcliversion: latest
        inlineScript: |
          az acr build \
            --registry ${{ env.AZURE_CONTAINER_REGISTRY }} \
            --image store-front:${{ github.sha }} \
            --file src/store-front/Dockerfile \
            src/store-front/
    # 1. Install kubelogin
    - name: Set up kubelogin
      uses: azure/use-kubelogin@v1
      with:
        kubelogin-version: 'v0.0.24'

    - name: Gets K8s context
      uses: azure/aks-set-context@v4
      with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}
          use-kubelogin: 'true' # This must be true to use the tool above
      id: login


    - name: Configure deployment
      uses: azure/k8s-bake@v3
      with:
        renderEngine: 'helm'
        helmChart: ${{ env.CHART_PATH }}
        overrides: |
          replicas:2
          image.repository:${{ env.REGISTRY_URL }}/${{ env.PROJECT_NAME }}
          image.tag:${{ github.sha }}
        helm-version: 'latest'
      id: bake


    - name: Deploys application
      uses: Azure/k8s-deploy@v5
      with:
        manifests: ${{ steps.bake.outputs.manifestsBundle }}
        images: |
          ${{ env.REGISTRY_URL }}/store-front:${{ github.sha }}
        imagepullsecrets: |
          ${{ env.PROJECT_NAME }}
